### ISSUE TITLE
confusing ocamltest reports

### ISSUE THREAD

**Issue by gasche** [ocaml/ocaml#9155]
I'm writing a new test for #463. In my branch, I observe the following output from ocamltest:

```
$ ../ocamltest/ocamltest.opt tests/utils/magic_number.ml
 ... testing 'magic_number.ml' with 1 (bytecode) => failed (The file /home/gasche/Prog/ocaml/github-trunk/testsuite/_ocamltest/tests/utils/magic_number/ocamlc.byte/magic_number.byte.output was expected to be empty because there is no reference file /home/gasche/Prog/ocaml/github-trunk/testsuite/tests/utils/magic_number.reference but it is not:
========================================

All tests succeeded.
========================================

)
```

It seems that the test fails (indeed I didn't write a `.reference` file yet), but at the same time there is a report that all tests succeeded. This is confusing and it looks like a bug.

**Comment by gasche** [comment]
(cc @shindere @nojb)

**Comment by damiendoligez** [comment]
@gasche the "All tests succeded" line is in the output of your test program, not the output of `ocamltest`. It's what you need to put into your reference file. You need to read carefully the error message that comes after the `failed` part. The closing paren is part of this message.

**Comment by gasche** [comment]
Here are some things that could have avoided the confusion:
- avoid using absolute paths in the error message, they make it very hard to read
- use the diff format as for normal test reports, so here all `+` at the beginning of the line, to clarify that this is part of a reference file

**Comment by gasche** [comment]
(Thanks for the comment, but personally I am skeptical that the issue is fixed or did not exist: the report remains confusing.)

**Comment by damiendoligez** [comment]
I agree that using the diff format would be the right thing to do, if only to have the same output as when the reference file is empty.

But in current trunk, `ocamltest` displays a lot more information about the failed test and it's become hard to confuse with a test that succeeds, so I would say problem solved.

**Comment by shindere** [comment]
@gasche I fully agree that absolute paths are difficult to read.

I however have to say I don't really know how to best handle paths. In
theory test outputs oculd be anywhere, e.g. under `/tmp`. And one may
also want to take into account the current working directory so in my
opinion the problem remains quite open, and at the same time not
fantastically interesting / exciting, it feels.
